In [1]:
#import library:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

<H1>DATA PREPARATION

In [2]:
#Check data in sale data file: 
sale_raw= pd.read_excel('data.xlsx')
sale_raw.head()

,visitor_id,43770,43771,43772,43773,43774,43775,43776,43777,43778,...,43860,43861,43862,43863,43864,43865,43866,43867,43868,43869
0,//02MonW5iVsFHTYioKFKD3J+v0=,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,//0Tw4uLP4F+KxJiH1MxeipBtlc=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,//1B47ThoPLHFC+ISAeK5lpiquc=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,//ioYjFoyckJezLI/waPP7iCqtg=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,//iPpNBcKX2/VuN7RTBSbDP9yBg=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
#Sale data need to be unpivoted to discover more: 
sale= sale_raw.melt(id_vars =['visitor_id'], var_name ='date', value_name ='no_of_order')
sale

                           visitor_id   date  no_of_order
0        //02MonW5iVsFHTYioKFKD3J+v0=  43770            0
1        //0Tw4uLP4F+KxJiH1MxeipBtlc=  43770            0
2        //1B47ThoPLHFC+ISAeK5lpiquc=  43770            0
3        //ioYjFoyckJezLI/waPP7iCqtg=  43770            0
4        //iPpNBcKX2/VuN7RTBSbDP9yBg=  43770            0
...                               ...    ...          ...
3943995  ZzvqjNiAiYOCnkxl27mQEL1PbZk=  43869            0
3943996  zzWdLg/Dyw9eyko6k+ZSDUuTio0=  43869            0
3943997  zzxiPB4vtRlO3eKR9TsP2+iQapc=  43869            0
3943998  ZzxNkankvZpO6O7TFz4wNb0KE3E=  43869            0
3943999                KhÃ¡ch vÃ£ng lai  43869          769

[3944000 rows x 3 columns]

In [4]:
#Drop day which have no order occurred:
sale_data= sale.drop(labels=sale.loc[sale['no_of_order']==0].index)
sale_data

                           visitor_id   date  no_of_order
237      /f4j8qx535UCFJNxx13w65G4Oio=  43770            1
276      /hYvcu32bHoLWxYT2XvPGvE7nWM=  43770            1
562      /w2K8geGTx+wX00VpxJiHeXfeJM=  43770            1
669      +2UZCewm6vsWZ51KA18TaQF5mIo=  43770            1
775      +Bs058M58ladlHd5UfAw6qiSQwo=  43770            3
...                               ...    ...          ...
3943633  ZPR2fSY3Syx0CEhnTHudbd+zWu0=  43869            1
3943698  zrcN/J8m8r3Nx/ZK+RKGDGPP6mk=  43869            1
3943710  ZRMYbrt66TGr3Ym45qAyna8vzdw=  43869            2
3943778  ZtRZJZTci1GqYL7vm9Kfs+bkH2M=  43869            4
3943999                KhÃ¡ch vÃ£ng lai  43869          769

[89084 rows x 3 columns]

In [5]:
#43770, 43771,...,43896 each number presents for each days from 1.11.2019
#Now I need to covert those number into datetime, excel handle this task better than Python, so I will export 
#this data set and covert in excel to save time: 
#save data: 
sale_data.to_excel("Sales data unpivot.xlsx", index = False)

KeyboardInterrupt:

In [7]:
#Import data with correct date time: 
sale_final= pd.read_excel('Sales_data_unpivot_correct datetime.xlsx')
sale_final

Exception ignored in: <function ZipFile.__del__ at 0x7f81c9c28670>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1807, in __del__
    self.close()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1824, in close
    self.fp.seek(self.start_dir)
ValueError: seek of closed file

                         visitor_id       date  no_of_order
0      /f4j8qx535UCFJNxx13w65G4Oio= 2019-11-01            1
1      /hYvcu32bHoLWxYT2XvPGvE7nWM= 2019-11-01            1
2      /w2K8geGTx+wX00VpxJiHeXfeJM= 2019-11-01            1
3      +2UZCewm6vsWZ51KA18TaQF5mIo= 2019-11-01            1
4      +Bs058M58ladlHd5UfAw6qiSQwo= 2019-11-01            3
...                             ...        ...          ...
89079  ZPR2fSY3Syx0CEhnTHudbd+zWu0= 2020-02-08            1
89080  zrcN/J8m8r3Nx/ZK+RKGDGPP6mk= 2020-02-08            1
89081  ZRMYbrt66TGr3Ym45qAyna8vzdw= 2020-02-08            2
89082  ZtRZJZTci1GqYL7vm9Kfs+bkH2M= 2020-02-08            4
89083                KhÃ¡ch vÃ£ng lai 2020-02-08          769

[89084 rows x 3 columns]

In [9]:
sale_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89084 entries, 0 to 89083
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   visitor_id   89084 non-null  object
 1   date         89084 non-null  datetime64[ns]
 2   no_of_order  89084 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 2.0+ MB

In [ ]:
#Create Month,Day, Year columns for furthur analysis:
sale_final['Day'] = pd.DatetimeIndex(sale_final['date']).day
sale_final['Month'] = pd.DatetimeIndex(sale_final['date']).month
sale_final['Year']= pd.DatetimeIndex(sale_final['date']).year
sale_final

In [ ]:
#Export Data to answer question 2:
sale_final.to_excel("Sale Data Final.xlsx", index = False)

In [ ]:
#Check data in vistor_id file: 
vistor = pd.read_csv('visitor_information.csv')
vistor